version: '3.8'

networks:
  default:

services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: conference-jpa
    ports:
      - "3030:3306"
    volumes:
      - "./.data/db:/var/lib/mysql"
    environment:
      MYSQL_DATABASE_PASSWORD: pass
      MYSQL_DATABASE: conference-jpa